import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar/Navbar"
import "../../node_modules/@fortawesome/fontawesome-free/css/all.min.css"
import { Toaster } from "@/components/ui/sonner"
import MySessionProvider from "@/MySessionProvider/MySessionProvider";
import Footer from "./_components/Footer/Footer";
import CartContextProvider from "@/contexts/CartContext";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script> */}
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} >
        <MySessionProvider>

          <CartContextProvider>
            <Toaster />
            <Navbar />
            <main>{children}</main>
            <Footer />
          </CartContextProvider>

        </MySessionProvider>

      </body>
    </html>
  );
}
